#! /bin/sh

sxhkd &
/usr/bin/compton --config /home/mk-parrot/.config/compton.conf &
wmname LG3D &
unclutter &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           4 
bspc config top_padding		22
bspc config focused_border_color "#d43a3a"
# bspc config automatic_scheme alternate

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plasma state=floating
bspc rule -a plasmashell state=floating border=off
bspc rule -a plasma-desktop state=floating
bspc rule -a krunner state=floating border=off
bspc rule -a Plasmoidviewer state=floating
bspc rule -a plasmawindowed state=floating
bspc rile -a Galculator state=floating
bspc rule -a Screenkey manage=off
